# deployment-phpfpm.yml - PHP-FPM Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devapi5-phpfpm
  namespace: ns-mcheva06
spec:
  replicas: 2
  selector:
    matchLabels:
      component: phpfpm
  template:
    metadata:
      labels:
        component: phpfpm
    spec:
      containers:
        - name: phpfpm
          image: ${HARBOR_REGISTRY_NO_PREFIX}/${CI_PROJECT}/devapi5-server:${CI_COMMIT_SHA}
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "mysql://udbsfapi:pdbsfapi@devapi5-database-service:3306/dbsfapi"
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              value: "your-secret-key-here-change-this-in-production"
            - name: APP_DEBUG
              value: "0"
          command: ["docker-entrypoint.sh"]
      imagePullSecrets:
        - name: gitlab-auth
