apiVersion: apps/v1
kind: Deployment
metadata:
  name: devapi5-database
  namespace: ns-mcheva06
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: dbsfapi
            - name: MYSQL_ROOT_PASSWORD
              value: rdbsfapi
            - name: MYSQL_USER
              value: udbsfapi
            - name: MYSQL_PASSWORD
              value: pdbsfapi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
