apiVersion: v1
kind: Service
metadata:
  name: devapi5-phpfpm-service
  namespace: ns-mcheva06
  labels:
    component: phpfpm
spec:
  type: ClusterIP
  selector:
    component: phpfpm
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
