apiVersion: v1
kind: Service
metadata:
  name: devapi5-service
  namespace: ns-mcheva06
  labels:
    component: web
spec:
  type: ClusterIP
  selector:
    component: nginx
  ports:
    - port: 80
      targetPort: 80
