name: Build and Deploy

on:
  push:
    branches:
      - master
      - CI

env:
  CI_PROJECT: 24h-web

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          set -e
          echo "Running front linters..."
          cd web
          npx eslint
          npx prettier --check .
          echo "No linter errors in front"
          echo "Running back linters..."
          cd ../sfapi
          php vendor/bin/php-cs-fixer fix --dry-run --diff
          echo "No linter errors in back"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          set -e
          echo "Running front tests..."
          cd web
          npm test
          echo "Running back tests..."
          cd ../sfapi
          php vendor/bin/phpunit --testdox

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect & execute script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd 24h-WEB
            . install.sh
