name: Build and Deploy

on:
  push:
    branches:
      - master
      - CI

env:
  CI_PROJECT: 24h-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect & execute script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd 24h-WEB
            . install.sh
